name: Upload

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true

jobs:
  merge_and_update:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Merge develop into master
      run: |
        git checkout master
        git merge origin/develop

    - name: Update version in Xcode project
      run: |
        ls
        /usr/libexec/PlistBuddy -c Print "Supporting Files/Info.plist"
        

    - name: Push changes
      run: git push origin master
